config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  devise_for :hosts
  devise_for :users
end

Rails.application.routes.draw do
  resources :trips do
    resources :events, to: 'static_pages#index'
  end
  resources :trips do
    resources :lodgings, to: 'static_pages#index'
  end
  resources :trips do
    resources :expenses, to: 'static_pages#index'
  end
  resources :trips do
    resources :map, to: 'static_pages#index'
  end
  resources :attendances
  resources :trips, only: [:new, :create, :index, :destroy, :edit]
end

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :trips do
        resources :events
        resources :lodgings
      end
      resources :events
      resources :lodgings
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  validates :user_id, uniqueness: {scope: :trip_id}
  belongs_to :trip
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :time, :address, :name, :date
  validates :name, length: { maximum: 50 }
  validates :details, length: { maximum: 140 }
  validates :expense, numericality: true
  belongs_to :trip
end

app/models/host.rb
class Host < ApplicationRecord
  has_many :trips
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lodging.rb
class Lodging < ApplicationRecord
  validates_presence_of :address, :check_in_time, :check_out_time, :check_in_date, :check_out_date
  validates :name, length: { maximum: 50 }
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates_presence_of :start_date, :end_date, :name, :password
  validates :password, uniqueness: true
  validates :name, length: { maximum: 20 }
  validates :image_link, format: {with: /\.(png|jpg)\Z/i}
  has_one :host
  has_many :events
  has_many :lodgings
  has_many :attendances
  has_many :users, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :trips, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController

  def index
    render json: Event.all
  end

  def show
    event = Event.find(params[:id])
    render json: event
  end

  def create
    event = Event.new(event_params)
    trip = event.trip
    trip.expenses += event.expense
    if event.save
      trip.save
      render json: { events: Event.all }
    else
      render json: { errors: event.errors.full_messages }
    end
  end

  def destroy
    event = Event.find(params[:id])
    trip = event.trip
    trip.expenses -= event.expense
    trip.save
    event.destroy
  end

  def event_params
    params.require(:event).permit(:name, :time, :date, :address, :expense, :details, :lat, :lng, :trip_id)
  end
end

app/controllers/api/v1/lodgings_controller.rb
class Api::V1::LodgingsController < ApiController

  def index
    render json: Lodging.all
  end

  def show
    lodging = Lodging.find(params[:id])
    render json: lodging
  end

  def create
    trip = Trip.find_by(id: lodging_params[:trip_id])
    lodging = Lodging.new(lodging_params)
    trip.expenses += lodging.expense
    if lodging.save
      trip.save
      render json: { lodgings: Lodging.all }
    else
      render json: { errors: lodging.errors.full_messages }
    end
  end

  def destroy
    lodging = Lodging.find(params[:id])
    trip = lodging.trip
    trip.expenses -= lodging.expense
    trip.save
    lodging.destroy
  end

  def lodging_params
    params.require(:lodging).permit(:name, :check_in_time, :check_out_time, :check_in_date, :check_out_date, :address, :expense, :lat, :lng, :trip_id)
  end
end

app/controllers/api/v1/trips_controller.rb
class Api::V1::TripsController < ApiController
  before_action :authenticate!

  def show
    trip = Trip.find(params[:id])
    lodgings = trip.lodgings.order('check_in_date ASC')
    events = trip.events.order('date ASC').order('time ASC')
    users = trip.users
    host = Host.find_by(id: trip.host_id)
    render json: {trip: trip, lodgings: lodgings, events: events, users: users, host: host}
  end

  def index
    if current_user
      trips = current_user.trips.order('start_date ASC')
    elsif current_host
      trips = current_host.trips.order('start_date ASC')
    end
    render json: {trips: trips}
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session

  def authenticate!
    if current_user
      :authenticate_user!
    elsif current_host
      :authenticate_host!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  before_action :authenticate_user!

  def new
    @attendance = Attendance.new
  end

  def create
    @password = password_params[:password]
    @password_validation = Trip.find_by(password: @password )
    @trip = attendance_params[:trip_id]
    if !@password_validation || @password_validation.id != @trip.to_i
      flash[:errors] = 'Invalid Trip Password and/or Trip ID'
    else
      @attendance = Attendance.new(trip_id: @trip.to_i, user_id: current_user.id)
      if
        @attendance.save
        flash.now[:success] = 'Trip joined!'
        redirect_to root_path
      else
        flash[:errors] = @attendance.errors.full_messages.join(', ')
      end
    end
  end

  def attendance_params
    params.require(:attendance).permit(:trip_id)
  end

  def password_params
    params.slice(:password)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :authenticate_host!

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.expenses = 0
    @trip.host_id = current_host.id
    if @trip.save
      redirect_to root_path
    else
      flash.now[:errors] = @trip.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @trips = current_host.trips
    if @trips == []
      flash[:errors] = "You are not currently hosting any trips"
      redirect_to root_path
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      flash.now[:errors] = @trip.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
    flash[:notice] = "The trip has been deleted."
  end


  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date, :password, :image_link)
  end

end

app/views/attendances/new.html.erb
<div class="new-article-form callout">
<%= form_for(@attendance) do |f| %>
<div class="field">
  <%= f.label :trip_id, 'Trip ID' %><br />
  <%= f.text_field :trip_id%>
</div>

<div class="field">
  <%= label :password, 'Enter Trip Password' %><br />
  <%= text_field_tag :password%>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>
</div>

<h5><%= link_to "Go Back to Home", root_path%></h5>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InteractiveItinerary</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA55jmLHtOaXD1oNo1azyznIrvTnTewjvg&libraries=places"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.4/foundation.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_pack_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="menu menu-hover-lines">
    <li class="active"><a href="/">Home</a>
      <%- if current_host -%>
      <li><%= link_to 'Manage Trips', trips_path %></li>
      <li><%= link_to 'Host a Trip', new_trip_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <%- elsif current_user -%>
      <li><%= link_to 'Join Trip', new_attendance_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <%- else -%>
      <li><%= link_to 'Become a Host', new_host_registration_path %></li>
      <li><%= link_to 'Sign in as Host', new_host_session_path %></li>
      <li><%= link_to 'Sign Up as Attendee', new_user_registration_path %></li>
      <li><%= link_to 'Sign In as Attendee', new_user_session_path %></li>
      <%- end -%>
    </ul>

    <div>
      <%- if !current_host && !current_user -%>
      <h1 id="map-key" class="callout"> Sign in to use Interactive Itinerary </h1>
      <%- end -%>
      <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <p class="callout"><%= value %></p>
      </div>
      <%- end -%>
    </div>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </body>
  </html>

app/views/static_pages/index.html.erb
<div id='app'></div>

app/views/trips/edit.html.erb
<div class="new-article-form callout">
  <%= form_for(@trip) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  
  <div class="field">
    <%= f.label :password, "Create Trip Password (Allows for others to join your trip):" %><br />
    <%= f.text_field :password%>
  </div>

  <div class="field">
    <%= f.label :image_link, "Add a .png or .jpg image link to spice up your itinerary:" %><br />
    <%= f.text_field :image_link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

<h5><%= link_to "Go Back to Home", root_path%></h5>

app/views/trips/index.html.erb
<% @trips.each do |trip| %>
<div class="columns small-6">
  <div class="card-info success">
    <div class="card-info-label">
      <div class="card-info-label-text">
        Share
      </div>
    </div>
    <div class="card-info-content">
      <h3 class="lead"> <%= trip.name %> </h3>
      <p>
        <ul><%= "Trip ID: #{trip.id}" %></ul>
        <ul><%= "Trip Password: #{trip.password}" %></ul>
        <% trip.users.each do |user| %>
        <h3 class="lead"> Attendance: </h3>
        <ul><%= user.email %></ul>
        <% end %>
        <div class="button-group-option" data-grouptype="OR">
          <a class="button success radius" <%= link_to "Edit Trip", edit_trip_path(trip) %></a>
          <a class="button primary radius" <%= link_to "Delete Trip", trip, method: :delete,
          data: { confirm: "Are you sure?" } %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/trips/new.html.erb
<div class="new-article-form callout">
  <%= form_for(@trip) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :password, "Create Trip Password (Allows for others to join your trip):" %><br />
    <%= f.text_field :password%>
  </div>

  <div class="field">
    <%= f.label :image_link, "Add a .png or .jpg image link to spice up your itinerary:" %><br />
    <%= f.text_field :image_link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

<h5><%= link_to "Go Back to Home", root_path%></h5>